# Generated by Django 4.2.27 on 2026-09-21 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0012_alter_cliente_options_alter_gastooperacional_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioBolsasAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_bolsa', models.CharField(choices=[('8_lav', 'Lavanda 8 kg'), ('20_lav', 'Lavanda 20 kg'), ('8_carbon', 'Carbón 8 kg'), ('20_carbon', 'Carbón 20 kg'), ('20_talco', 'Talco 20 kg'), ('20_cafe', 'Café 20 kg')], max_length=20)),
                ('stock_sistema_before', models.IntegerField(help_text='Stock calculado por sistema antes del ajuste')),
                ('stock_fisico', models.IntegerField(help_text='Conteo físico ingresado por usuario (entero >= 0)')),
                ('diferencia', models.IntegerField(editable=False, help_text='Automático: stock_fisico - stock_sistema_before')),
                ('motivo', models.CharField(choices=[('inf', 'Inventario físico'), ('ed', 'Error detectado'), ('mp', 'Merma / pérdida'), ('dv', 'Devolución / recuperación'), ('otro', 'Otro')], max_length=10)),
                ('observacion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_inventario_bolsas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste Inventario Bolsas',
                'verbose_name_plural': 'Ajustes Inventario Bolsas',
                'ordering': ['-fecha'],
            },
        ),
    ]
